# Generated by Django 5.0.1 on 2024-02-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_exercises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='exercise',
            field=models.TextField(max_length=100),
        ),
    ]
